import { t, P, slider, globals } from './helpers.js';
import { main as mesh } from '../nodes/mesh.js';
import { main as aurora } from '../nodes/aurora.js';
import { main as liquid } from '../nodes/liquid.js';
import { main as flow } from '../nodes/flow.js';
import { main as grain } from '../nodes/grain.js';
import { main as iridescent } from '../nodes/iridescent.js';
import { main as blobs } from '../nodes/blobs.js';
import { main as orbs } from '../nodes/orbs.js';

/** @type {import('../registry.js').Background[]} */
export const gradients = [
    {
        id: 'mesh',
        category: 'gradient',
        cost: 'light',
        renderScale: 0.5,
        mouse: false,
        speed: 0.5,
        palette: [P(0.58, 0.25, 285), P(0.72, 0.24, 350), P(0.82, 0.17, 60), P(0.68, 0.16, 215)],
        name: t('Mesh Gradient', 'Mesh Gradient'),
        description: t(
            'Four drifting color anchors blended in OKLab: the silky gradient of modern SaaS landings.',
            'Cuatro anclas de color a la deriva mezcladas en OKLab: el degradado sedoso de las landings modernas.',
        ),
        colorLabels: { en: ['Color 1', 'Color 2', 'Color 3', 'Color 4'], es: ['Color 1', 'Color 2', 'Color 3', 'Color 4'] },
        controls: [
            ...globals({ noise: 0.06 }),
            slider('mesh-scale', 'u_scale', [0.5, 2.0, 0.05, 0.85],
                t('Blob size', 'Tamaño'), t('How far each color spreads before blending.', 'Cuánto se expande cada color antes de mezclarse.')),
            slider('mesh-distortion', 'u_distortion', [0, 1.5, 0.05, 0.6],
                t('Warp', 'Ondulación'), t('Amount of organic warping applied to the mesh.', 'Cantidad de deformación orgánica de la malla.')),
        ],
        main: mesh,
        source: () => import('../nodes/mesh.js?raw'),
    },
    {
        id: 'aurora',
        category: 'gradient',
        cost: 'heavy',
        renderScale: 0.6,
        mouse: false,
        speed: 0.5,
        palette: [P(0.2, 0.06, 265), P(0.78, 0.2, 155), P(0.75, 0.14, 195), P(0.7, 0.2, 320)],
        name: t('Aurora', 'Aurora'),
        description: t(
            'Northern lights: luminous curtains with ray structure over a starry night sky.',
            'Auroras boreales: cortinas luminosas con rayos sobre un cielo nocturno estrellado.',
        ),
        colorLabels: {
            en: ['Night sky', 'Curtain', 'Secondary', 'Fringe'],
            es: ['Cielo nocturno', 'Cortina', 'Secundario', 'Borde'],
        },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('aurora-intensity', 'u_intensity', [0.3, 2.0, 0.05, 1.0],
                t('Intensity', 'Intensidad'), t('Brightness of the light curtains.', 'Brillo de las cortinas de luz.')),
            slider('aurora-scale', 'u_scale', [0.5, 2.0, 0.05, 1.0],
                t('Width', 'Ancho'), t('Horizontal size of the curtains.', 'Tamaño horizontal de las cortinas.')),
            slider('aurora-stars', 'u_density', [0, 1, 0.05, 0.5],
                t('Stars', 'Estrellas'), t('How many stars twinkle in the sky.', 'Cuántas estrellas titilan en el cielo.')),
        ],
        main: aurora,
        source: () => import('../nodes/aurora.js?raw'),
    },
    {
        id: 'liquid',
        category: 'gradient',
        cost: 'light',
        renderScale: 0.6,
        mouse: false,
        speed: 0.45,
        palette: [P(0.22, 0.06, 265), P(0.5, 0.16, 270), P(0.8, 0.08, 230), P(0.96, 0.02, 220)],
        name: t('Liquid Chrome', 'Cromo líquido'),
        description: t(
            'Molten metal: a warped height field lit like a mirror, with soft reflections.',
            'Metal fundido: un campo de alturas deformado e iluminado como un espejo, con reflejos suaves.',
        ),
        colorLabels: { en: ['Shadow', 'Body', 'Light', 'Highlight'], es: ['Sombra', 'Cuerpo', 'Luz', 'Brillo'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('liquid-scale', 'u_scale', [0.5, 2.5, 0.05, 1.0],
                t('Scale', 'Escala'), t('Size of the liquid folds.', 'Tamaño de los pliegues del líquido.')),
            slider('liquid-warp', 'u_distortion', [0.2, 1.5, 0.05, 0.8],
                t('Warp', 'Torsión'), t('How much the surface twists on itself.', 'Cuánto se retuerce la superficie sobre sí misma.')),
        ],
        main: liquid,
        source: () => import('../nodes/liquid.js?raw'),
    },
    {
        id: 'flow',
        category: 'gradient',
        cost: 'heavy',
        renderScale: 0.5,
        mouse: false,
        speed: 0.4,
        palette: [P(0.3, 0.12, 300), P(0.55, 0.2, 320), P(0.75, 0.15, 10), P(0.92, 0.07, 70)],
        name: t('Silk Flow', 'Seda etérea'),
        description: t(
            'Long, silky folds of warped noise with a soft satin sheen.',
            'Pliegues largos y sedosos de ruido deformado con un suave brillo satinado.',
        ),
        colorLabels: { en: ['Deep', 'Mid', 'Light', 'Glow'], es: ['Profundo', 'Medio', 'Claro', 'Brillo'] },
        controls: [
            ...globals({ noise: 0.04 }),
            slider('flow-scale', 'u_scale', [0.5, 3.0, 0.05, 1.4],
                t('Scale', 'Escala'), t('Size of the silk folds.', 'Tamaño de los pliegues de seda.')),
        ],
        main: flow,
        source: () => import('../nodes/flow.js?raw'),
    },
    {
        id: 'grain',
        category: 'gradient',
        cost: 'light',
        renderScale: 1,
        mouse: false,
        speed: 0.4,
        palette: [P(0.28, 0.12, 280), P(0.55, 0.22, 350), P(0.75, 0.17, 50), P(0.95, 0.08, 95)],
        name: t('Grain Gradient', 'Degradado granulado'),
        description: t(
            'Risograph-style gradient: soft shapes that dissolve into stippled grain.',
            'Degradado estilo risografía: formas suaves que se disuelven en un granulado punteado.',
        ),
        colorLabels: { en: ['Base', 'Mid', 'Warm', 'Light'], es: ['Base', 'Medio', 'Cálido', 'Claro'] },
        controls: [
            ...globals({ noise: 0.08 }),
            slider('grain-stipple', 'u_intensity', [0, 1.5, 0.05, 0.7],
                t('Stipple', 'Punteado'), t('How strongly the grain breaks up the color transitions.', 'Cuánto rompe el grano las transiciones de color.')),
        ],
        main: grain,
        source: () => import('../nodes/grain.js?raw'),
    },
    {
        id: 'iridescent',
        category: 'gradient',
        cost: 'light',
        renderScale: 0.6,
        mouse: false,
        speed: 0.4,
        palette: [P(0.85, 0.1, 330), P(0.88, 0.1, 200), P(0.9, 0.1, 120), P(0.85, 0.12, 280)],
        name: t('Iridescent', 'Iridiscente'),
        description: t(
            'Holographic foil: thin-film color shifts with a metallic sheen.',
            'Lámina holográfica: cambios de color de película fina con brillo metálico.',
        ),
        colorLabels: { en: ['Tone 1', 'Tone 2', 'Tone 3', 'Tone 4'], es: ['Tono 1', 'Tono 2', 'Tono 3', 'Tono 4'] },
        controls: [
            ...globals({ noise: 0.04 }),
            slider('iri-scale', 'u_scale', [0.5, 2.5, 0.05, 1.2],
                t('Scale', 'Escala'), t('Size of the interference pattern.', 'Tamaño del patrón de interferencia.')),
            slider('iri-warp', 'u_distortion', [0, 1.5, 0.05, 0.8],
                t('Warp', 'Torsión'), t('How much the foil bends.', 'Cuánto se curva la lámina.')),
            slider('iri-bands', 'u_density', [0, 1, 0.05, 0.5],
                t('Bands', 'Bandas'), t('How many color cycles fit on screen.', 'Cuántos ciclos de color caben en pantalla.')),
        ],
        main: iridescent,
        source: () => import('../nodes/iridescent.js?raw'),
    },
    {
        id: 'blobs',
        category: 'gradient',
        cost: 'light',
        renderScale: 0.75,
        mouse: true,
        speed: 0.5,
        palette: [P(0.18, 0.07, 300), P(0.42, 0.2, 320), P(0.68, 0.24, 350), P(0.88, 0.14, 60)],
        name: t('Lava Blobs', 'Lámpara de lava'),
        description: t(
            'Metaballs drifting and merging, one of them chasing your pointer.',
            'Metabolas que se mueven y se funden, una de ellas persigue tu puntero.',
        ),
        colorLabels: { en: ['Background', 'Halo', 'Blob', 'Core'], es: ['Fondo', 'Halo', 'Gota', 'Núcleo'] },
        controls: [
            ...globals({ noise: 0.04 }),
            slider('blobs-size', 'u_size', [0.5, 2.0, 0.05, 1.0],
                t('Blob size', 'Tamaño'), t('Radius of the blobs.', 'Radio de las gotas.')),
            slider('blobs-softness', 'u_softness', [0, 1, 0.05, 0.3],
                t('Softness', 'Suavidad'), t('How soft the blob edges are.', 'Qué tan suaves son los bordes.')),
        ],
        main: blobs,
        source: () => import('../nodes/blobs.js?raw'),
    },
    {
        id: 'orbs',
        category: 'gradient',
        cost: 'light',
        renderScale: 0.75,
        mouse: false,
        speed: 0.5,
        palette: [P(0.2, 0.07, 270), P(0.6, 0.2, 300), P(0.7, 0.2, 340), P(0.85, 0.14, 200)],
        name: t('Glow Orbs', 'Orbes de luz'),
        description: t(
            'Soft bokeh orbs floating up in parallax layers over a deep vignette.',
            'Orbes de luz tipo bokeh que flotan en capas con paralaje sobre una viñeta profunda.',
        ),
        colorLabels: { en: ['Background', 'Orb 1', 'Orb 2', 'Orb 3'], es: ['Fondo', 'Orbe 1', 'Orbe 2', 'Orbe 3'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('orbs-size', 'u_size', [0.5, 1.8, 0.05, 1.0],
                t('Orb size', 'Tamaño'), t('Size of the orbs.', 'Tamaño de los orbes.')),
            slider('orbs-density', 'u_density', [0, 1, 0.05, 0.5],
                t('Density', 'Densidad'), t('How many orbs fill the screen.', 'Cuántos orbes llenan la pantalla.')),
            slider('orbs-softness', 'u_softness', [0, 1, 0.05, 0.6],
                t('Softness', 'Suavidad'), t('How blurry the orbs are.', 'Qué tan difuminados están los orbes.')),
        ],
        main: orbs,
        source: () => import('../nodes/orbs.js?raw'),
    },
];
