import { t, P, slider, globals } from './helpers.js';
import { main as waves } from '../nodes/waves.js';
import { main as stripes } from '../nodes/stripes.js';
import { main as geometric } from '../nodes/geometric.js';
import { main as dots } from '../nodes/dots.js';
import { main as grid } from '../nodes/grid.js';
import { main as topo } from '../nodes/topo.js';
import { main as voronoi } from '../nodes/voronoi.js';
import { main as plasma } from '../nodes/plasma.js';

/** @type {import('../registry.js').Background[]} */
export const patterns = [
    {
        id: 'waves',
        category: 'pattern',
        cost: 'light',
        renderScale: 1,
        mouse: false,
        speed: 0.5,
        palette: [P(0.2, 0.08, 260), P(0.45, 0.15, 250), P(0.65, 0.14, 225), P(0.85, 0.1, 200)],
        name: t('Layered Waves', 'Olas en capas'),
        description: t(
            'Five translucent wave layers rolling back to front, with glowing crests.',
            'Cinco capas de olas translúcidas de fondo a frente, con crestas brillantes.',
        ),
        colorLabels: { en: ['Backdrop', 'Far wave', 'Mid wave', 'Front wave'], es: ['Fondo', 'Ola lejana', 'Ola media', 'Ola frontal'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('waves-amplitude', 'u_amplitude', [0.2, 2.0, 0.05, 1.0],
                t('Amplitude', 'Amplitud'), t('Height of the waves.', 'Altura de las olas.')),
            slider('waves-frequency', 'u_frequency', [0.4, 2.5, 0.05, 1.0],
                t('Frequency', 'Frecuencia'), t('How many waves fit across the screen.', 'Cuántas olas caben en la pantalla.')),
        ],
        main: waves,
        source: () => import('../nodes/waves.js?raw'),
    },
    {
        id: 'stripes',
        category: 'pattern',
        cost: 'light',
        renderScale: 1,
        mouse: false,
        speed: 0.5,
        palette: [P(0.3, 0.15, 290), P(0.6, 0.22, 350), P(0.78, 0.17, 60), P(0.9, 0.1, 110)],
        name: t('Soft Stripes', 'Rayas suaves'),
        description: t(
            'Slanted bands that slide and sway, walking through the palette.',
            'Bandas inclinadas que se deslizan y ondulan, recorriendo la paleta.',
        ),
        colorLabels: { en: ['Tone 1', 'Tone 2', 'Tone 3', 'Tone 4'], es: ['Tono 1', 'Tono 2', 'Tono 3', 'Tono 4'] },
        controls: [
            ...globals({ noise: 0.04 }),
            slider('stripes-density', 'u_density', [0, 1, 0.05, 0.3],
                t('Density', 'Densidad'), t('Number of stripes.', 'Cantidad de rayas.')),
            slider('stripes-angle', 'u_rotation', [0, 3.14, 0.05, 0.6],
                t('Angle', 'Ángulo'), t('Direction of the stripes.', 'Dirección de las rayas.')),
            slider('stripes-softness', 'u_softness', [0, 1, 0.05, 0.3],
                t('Softness', 'Suavidad'), t('How much neighbouring stripes blend.', 'Cuánto se mezclan las rayas vecinas.')),
            slider('stripes-warp', 'u_distortion', [0, 1.5, 0.05, 0.6],
                t('Sway', 'Ondulación'), t('How much the stripes wobble.', 'Cuánto se ondulan las rayas.')),
        ],
        main: stripes,
        source: () => import('../nodes/stripes.js?raw'),
    },
    {
        id: 'geometric',
        category: 'pattern',
        cost: 'light',
        renderScale: 1,
        mouse: false,
        speed: 0.5,
        palette: [P(0.22, 0.08, 280), P(0.4, 0.15, 290), P(0.6, 0.18, 310), P(0.9, 0.14, 200)],
        name: t('Hex Grid', 'Rejilla hexagonal'),
        description: t(
            'Hexagonal tiling where each cell breathes in a travelling wave and the edges glow.',
            'Teselado hexagonal donde cada celda respira en una onda y los bordes brillan.',
        ),
        colorLabels: { en: ['Base', 'Cells', 'Cells light', 'Edge glow'], es: ['Base', 'Celdas', 'Celdas claras', 'Brillo de borde'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('geo-scale', 'u_scale', [2, 16, 0.5, 6],
                t('Cell size', 'Tamaño'), t('Number of hexagons across the screen.', 'Cantidad de hexágonos en la pantalla.')),
            slider('geo-edge', 'u_thickness', [0.2, 2.5, 0.05, 1.0],
                t('Edge', 'Borde'), t('Thickness of the glowing edges.', 'Grosor de los bordes brillantes.')),
            slider('geo-rotation', 'u_rotation', [0, 3.14, 0.05, 0],
                t('Rotation', 'Rotación'), t('Rotates the whole grid.', 'Rota toda la rejilla.')),
        ],
        main: geometric,
        source: () => import('../nodes/geometric.js?raw'),
    },
    {
        id: 'dots',
        category: 'pattern',
        cost: 'light',
        renderScale: 1,
        mouse: true,
        speed: 0.5,
        palette: [P(0.16, 0.05, 280), P(0.25, 0.08, 285), P(0.7, 0.2, 340), P(0.92, 0.14, 95)],
        name: t('Dot Grid', 'Rejilla de puntos'),
        description: t(
            'A halftone dot screen that swells with travelling waves and follows your pointer.',
            'Una trama de puntos que crece con ondas viajeras y sigue tu puntero.',
        ),
        colorLabels: { en: ['Background', 'Backdrop glow', 'Dots', 'Dot highlight'], es: ['Fondo', 'Brillo de fondo', 'Puntos', 'Resalte'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('dots-density', 'u_density', [0, 1, 0.05, 0.4],
                t('Density', 'Densidad'), t('How many dots fit on screen.', 'Cuántos puntos caben en la pantalla.')),
            slider('dots-size', 'u_size', [0.5, 1.6, 0.05, 1.0],
                t('Dot size', 'Tamaño'), t('Overall size of the dots.', 'Tamaño general de los puntos.')),
            slider('dots-wave', 'u_distortion', [0, 1.5, 0.05, 0.8],
                t('Wave', 'Onda'), t('Strength of the travelling wave.', 'Fuerza de la onda viajera.')),
        ],
        main: dots,
        source: () => import('../nodes/dots.js?raw'),
    },
    {
        id: 'grid',
        category: 'pattern',
        cost: 'light',
        renderScale: 1,
        mouse: true,
        speed: 0.5,
        palette: [P(0.14, 0.04, 265), P(0.26, 0.09, 270), P(0.6, 0.18, 255), P(0.85, 0.14, 200)],
        name: t('Glow Grid', 'Rejilla luminosa'),
        description: t(
            'Fine technical grid fading to the edges, with rings of light and a glow under the pointer.',
            'Rejilla técnica fina que se desvanece en los bordes, con anillos de luz y un brillo bajo el puntero.',
        ),
        colorLabels: { en: ['Background', 'Backdrop glow', 'Lines', 'Light'], es: ['Fondo', 'Brillo de fondo', 'Líneas', 'Luz'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('grid-density', 'u_density', [0, 1, 0.05, 0.4],
                t('Density', 'Densidad'), t('How many cells fit on screen.', 'Cuántas celdas caben en la pantalla.')),
            slider('grid-line', 'u_thickness', [0.4, 2.5, 0.05, 1.0],
                t('Line weight', 'Grosor'), t('Thickness of the grid lines.', 'Grosor de las líneas de la rejilla.')),
            slider('grid-glow', 'u_glow', [0, 2, 0.05, 1.0],
                t('Glow', 'Resplandor'), t('Intensity of the travelling light.', 'Intensidad de la luz viajera.')),
        ],
        main: grid,
        source: () => import('../nodes/grid.js?raw'),
    },
    {
        id: 'topo',
        category: 'pattern',
        cost: 'medium',
        renderScale: 1,
        mouse: false,
        speed: 0.4,
        palette: [P(0.2, 0.05, 210), P(0.34, 0.08, 200), P(0.5, 0.1, 175), P(0.9, 0.13, 100)],
        name: t('Topographic', 'Topográfico'),
        description: t(
            'Contour lines of a drifting terrain, with bolder index contours and hill shading.',
            'Curvas de nivel de un terreno cambiante, con curvas maestras más marcadas y sombreado.',
        ),
        colorLabels: { en: ['Lowlands', 'Plains', 'Highlands', 'Contour lines'], es: ['Valles', 'Llanuras', 'Montañas', 'Curvas de nivel'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('topo-scale', 'u_scale', [0.5, 2.5, 0.05, 1.0],
                t('Scale', 'Escala'), t('Size of the terrain features.', 'Tamaño de las formas del terreno.')),
            slider('topo-lines', 'u_density', [0, 1, 0.05, 0.5],
                t('Lines', 'Líneas'), t('Number of contour levels.', 'Cantidad de curvas de nivel.')),
            slider('topo-weight', 'u_thickness', [0.4, 2.5, 0.05, 1.0],
                t('Line weight', 'Grosor'), t('Thickness of the contour lines.', 'Grosor de las curvas de nivel.')),
        ],
        main: topo,
        source: () => import('../nodes/topo.js?raw'),
    },
    {
        id: 'voronoi',
        category: 'pattern',
        cost: 'medium',
        renderScale: 0.8,
        mouse: false,
        speed: 0.5,
        palette: [P(0.22, 0.1, 300), P(0.4, 0.18, 320), P(0.62, 0.2, 350), P(0.9, 0.12, 90)],
        name: t('Cells', 'Células'),
        description: t(
            'Animated Voronoi: every cell gets a tone and a soft inner glow, with bright borders.',
            'Voronoi animado: cada célula tiene un tono y un brillo interior suave, con bordes luminosos.',
        ),
        colorLabels: { en: ['Cells deep', 'Cells mid', 'Cells light', 'Borders'], es: ['Celdas oscuras', 'Celdas medias', 'Celdas claras', 'Bordes'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('cells-density', 'u_density', [0, 1, 0.05, 0.4],
                t('Cells', 'Celdas'), t('How many cells fit on screen.', 'Cuántas celdas caben en la pantalla.')),
            slider('cells-border', 'u_thickness', [0.2, 2.5, 0.05, 1.0],
                t('Border', 'Borde'), t('Thickness of the cell borders.', 'Grosor de los bordes de las celdas.')),
        ],
        main: voronoi,
        source: () => import('../nodes/voronoi.js?raw'),
    },
    {
        id: 'plasma',
        category: 'pattern',
        cost: 'light',
        renderScale: 0.5,
        mouse: false,
        speed: 0.5,
        palette: [P(0.25, 0.15, 300), P(0.55, 0.25, 340), P(0.78, 0.18, 60), P(0.65, 0.2, 200)],
        name: t('Plasma', 'Plasma'),
        description: t(
            'The demoscene classic: overlapping sine fields rippling the palette into shifting bands.',
            'El clásico de la demoscene: campos sinusoidales superpuestos que ondulan la paleta en bandas cambiantes.',
        ),
        colorLabels: { en: ['Tone 1', 'Tone 2', 'Tone 3', 'Tone 4'], es: ['Tono 1', 'Tono 2', 'Tono 3', 'Tono 4'] },
        controls: [
            ...globals({ noise: 0.03 }),
            slider('plasma-scale', 'u_scale', [0.5, 2.5, 0.05, 1.0],
                t('Scale', 'Escala'), t('Size of the plasma features.', 'Tamaño de las formas del plasma.')),
            slider('plasma-warp', 'u_distortion', [0, 1.5, 0.05, 0.7],
                t('Warp', 'Torsión'), t('How much the field twists.', 'Cuánto se retuerce el campo.')),
            slider('plasma-bands', 'u_density', [0, 1, 0.05, 0.4],
                t('Bands', 'Bandas'), t('How many color cycles fit on screen.', 'Cuántos ciclos de color caben en pantalla.')),
        ],
        main: plasma,
        source: () => import('../nodes/plasma.js?raw'),
    },
];
